import type { Product } from "./types";
import type {
  ProductBrand,
  ProductBrandLocalization,
  ProductCategory,
  ProductCategoryLocalization,
  ProductLocalization,
  ProductSeo,
} from "./catalog";
import type { ProductSku } from "./sku";
import type { ProductPrice } from "./pricing";
import type { ProductMediaItem } from "./media";
import type {
  ProductAttribute,
  ProductSpecification,
} from "./attributes";

const DATE = "2026-01-01T00:00:00.000Z";

type SeedItem = {
  id: string;
  categoryId: string;
  en: string;
  fa: string;
  descriptionEn: string;
  descriptionFa: string;
  price: number;
  compareAtPrice?: number;
  sku: string;
};

const categories: Array<{
  id: string;
  en: string;
  fa: string;
  slug: string;
}> = [
  { id: "wearables", en: "Wearables", fa: "Ù¾ÙˆØ´ÛŒØ¯Ù†ÛŒâ€ŒÙ‡Ø§", slug: "wearables" },
  { id: "audio", en: "Audio", fa: "ØµÙˆØªÛŒ", slug: "audio" },
  { id: "computing", en: "Computing", fa: "Ø±Ø§ÛŒØ§Ù†Ù‡", slug: "computing" },
  { id: "home", en: "Home", fa: "Ø®Ø§Ù†Ù‡", slug: "home" },
  { id: "smart-tech", en: "Smart Tech", fa: "ÙÙ†Ø§ÙˆØ±ÛŒ Ù‡ÙˆØ´Ù…Ù†Ø¯", slug: "smart-tech" },
  { id: "lifestyle", en: "Lifestyle", fa: "Ø³Ø¨Ú© Ø²Ù†Ø¯Ú¯ÛŒ", slug: "lifestyle" },
  { id: "gaming", en: "Gaming", fa: "Ú¯ÛŒÙ…ÛŒÙ†Ú¯", slug: "gaming" },
  { id: "mobile", en: "Mobile & Tablets", fa: "Ù…ÙˆØ¨Ø§ÛŒÙ„ Ùˆ ØªØ¨Ù„Øª", slug: "mobile-tablets" },
  { id: "kitchen", en: "Kitchen", fa: "Ø¢Ø´Ù¾Ø²Ø®Ø§Ù†Ù‡", slug: "kitchen" },
  { id: "bags", en: "Bags", fa: "Ú©ÛŒÙ", slug: "bags" },
  { id: "jewelry", en: "Jewelry", fa: "Ø²ÛŒÙˆØ±Ø¢Ù„Ø§Øª", slug: "jewelry" },
  { id: "personal-care", en: "Personal Care", fa: "Ù„ÙˆØ§Ø²Ù… Ø´Ø®ØµÛŒ", slug: "personal-care" },
];

export const productCategories: ProductCategory[] = categories.map((category) => ({
  id: category.id,
  status: "active",
}));

export const categoryLocalizations: ProductCategoryLocalization[] =
  categories.flatMap((category) => [
    {
      categoryId: category.id,
      locale: "en",
      name: category.en,
      slug: category.slug,
    },
    {
      categoryId: category.id,
      locale: "fa",
      name: category.fa,
      slug: category.slug,
    },
  ]);

export const productBrands: ProductBrand[] = [];
export const brandLocalizations: ProductBrandLocalization[] = [];

const seedItems: SeedItem[] = [
  {
    id: "smart-watch-pro",
    categoryId: "wearables",
    en: "Smart Watch Pro",
    fa: "Ø³Ø§Ø¹Øª Ù‡ÙˆØ´Ù…Ù†Ø¯ Ù¾Ø±Ùˆ",
    descriptionEn: "Smart wearable with health tracking and notifications.",
    descriptionFa: "Ø³Ø§Ø¹Øª Ù‡ÙˆØ´Ù…Ù†Ø¯ Ø¨Ø§ Ù¾Ø§ÛŒØ´ Ø³Ù„Ø§Ù…Øª Ùˆ Ø§Ø¹Ù„Ø§Ù†â€ŒÙ‡Ø§ÛŒ Ù…ÙˆØ¨Ø§ÛŒÙ„.",
    price: 89,
    compareAtPrice: 119,
    sku: "YAS-SWP-001",
  },
  {
    id: "fitness-band-active",
    categoryId: "wearables",
    en: "Fitness Band Active",
    fa: "Ø¯Ø³ØªØ¨Ù†Ø¯ ÙˆØ±Ø²Ø´ÛŒ Active",
    descriptionEn: "Light fitness band for activity and daily tracking.",
    descriptionFa: "Ø¯Ø³ØªØ¨Ù†Ø¯ Ø³Ø¨Ú© Ø¨Ø±Ø§ÛŒ ÙØ¹Ø§Ù„ÛŒØª ÙˆØ±Ø²Ø´ÛŒ Ùˆ Ù¾Ø§ÛŒØ´ Ø±ÙˆØ²Ø§Ù†Ù‡.",
    price: 39,
    compareAtPrice: 49,
    sku: "YAS-FBA-002",
  },
  {
    id: "wireless-headphones",
    categoryId: "audio",
    en: "Wireless Headphones",
    fa: "Ù‡Ø¯ÙÙˆÙ† Ø¨ÛŒâ€ŒØ³ÛŒÙ…",
    descriptionEn: "Comfortable wireless headphones for music and work.",
    descriptionFa: "Ù‡Ø¯ÙÙˆÙ† Ø¨ÛŒâ€ŒØ³ÛŒÙ… Ø±Ø§Ø­Øª Ø¨Ø±Ø§ÛŒ Ù…ÙˆØ³ÛŒÙ‚ÛŒ Ùˆ Ú©Ø§Ø±.",
    price: 74,
    compareAtPrice: 99,
    sku: "YAS-WH-001",
  },
  {
    id: "airflow-earbuds",
    categoryId: "audio",
    en: "AirFlow Earbuds",
    fa: "Ø§ÛŒØ±Ø¨Ø§Ø¯ AirFlow",
    descriptionEn: "Compact wireless earbuds for everyday listening.",
    descriptionFa: "Ø§ÛŒØ±Ø¨Ø§Ø¯ Ø¨ÛŒâ€ŒØ³ÛŒÙ… Ú©ÙˆÚ†Ú© Ø¨Ø±Ø§ÛŒ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø±ÙˆØ²Ù…Ø±Ù‡.",
    price: 69,
    compareAtPrice: 89,
    sku: "YAS-AE-001",
  },
  {
    id: "studio-usb-microphone",
    categoryId: "audio",
    en: "Studio USB Microphone",
    fa: "Ù…ÛŒÚ©Ø±ÙˆÙÙˆÙ† USB Ø§Ø³ØªÙˆØ¯ÛŒÙˆ",
    descriptionEn: "USB microphone for streaming, calls and recording.",
    descriptionFa: "Ù…ÛŒÚ©Ø±ÙˆÙÙˆÙ† USB Ø¨Ø±Ø§ÛŒ Ø§Ø³ØªØ±ÛŒÙ…ØŒ ØªÙ…Ø§Ø³ Ùˆ Ø¶Ø¨Ø· ØµØ¯Ø§.",
    price: 79,
    compareAtPrice: 99,
    sku: "YAS-SUM-003",
  },
  {
    id: "ultra-keyboard",
    categoryId: "computing",
    en: "Ultra Keyboard",
    fa: "Ú©ÛŒØ¨ÙˆØ±Ø¯ Ø§ÙˆÙ„ØªØ±Ø§",
    descriptionEn: "Modern wireless keyboard for work and productivity.",
    descriptionFa: "Ú©ÛŒØ¨ÙˆØ±Ø¯ Ø¨ÛŒâ€ŒØ³ÛŒÙ… Ù…Ø¯Ø±Ù† Ø¨Ø±Ø§ÛŒ Ú©Ø§Ø± Ùˆ Ø¨Ù‡Ø±Ù‡â€ŒÙˆØ±ÛŒ.",
    price: 59,
    compareAtPrice: 79,
    sku: "YAS-UK-001",
  },
  {
    id: "precision-mouse",
    categoryId: "computing",
    en: "Precision Mouse",
    fa: "Ù…Ø§ÙˆØ³ Precision",
    descriptionEn: "Ergonomic mouse for office and creative work.",
    descriptionFa: "Ù…Ø§ÙˆØ³ Ø§Ø±Ú¯ÙˆÙ†ÙˆÙ…ÛŒÚ© Ø¨Ø±Ø§ÛŒ Ú©Ø§Ø± Ø§Ø¯Ø§Ø±ÛŒ Ùˆ Ø®Ù„Ø§Ù‚Ø§Ù†Ù‡.",
    price: 35,
    compareAtPrice: 45,
    sku: "YAS-PM-004",
  },
  {
    id: "usb-c-hub-pro",
    categoryId: "computing",
    en: "USB-C Hub Pro",
    fa: "Ù‡Ø§Ø¨ USB-C Ù¾Ø±Ùˆ",
    descriptionEn: "Multi-port USB-C hub for laptops and tablets.",
    descriptionFa: "Ù‡Ø§Ø¨ Ú†Ù†Ø¯Ù¾ÙˆØ±ØªÙ‡ USB-C Ø¨Ø±Ø§ÛŒ Ù„Ù¾â€ŒØªØ§Ù¾ Ùˆ ØªØ¨Ù„Øª.",
    price: 45,
    compareAtPrice: 59,
    sku: "YAS-UCH-005",
  },
  {
    id: "smart-desk-lamp",
    categoryId: "home",
    en: "Smart Desk Lamp",
    fa: "Ú†Ø±Ø§Øº Ø±ÙˆÙ…ÛŒØ²ÛŒ Ù‡ÙˆØ´Ù…Ù†Ø¯",
    descriptionEn: "Adjustable smart desk lighting for work and study.",
    descriptionFa: "Ú†Ø±Ø§Øº Ø±ÙˆÙ…ÛŒØ²ÛŒ Ù‡ÙˆØ´Ù…Ù†Ø¯ Ø¨Ø§ Ù†ÙˆØ± Ù‚Ø§Ø¨Ù„ ØªÙ†Ø¸ÛŒÙ… Ø¨Ø±Ø§ÛŒ Ú©Ø§Ø± Ùˆ Ù…Ø·Ø§Ù„Ø¹Ù‡.",
    price: 42,
    compareAtPrice: 56,
    sku: "YAS-SDL-001",
  },
  {
    id: "glow-ambient-light",
    categoryId: "home",
    en: "Glow Ambient Light",
    fa: "Ú†Ø±Ø§Øº Ù†ÙˆØ±Ù¾Ø±Ø¯Ø§Ø²ÛŒ Glow",
    descriptionEn: "Ambient light for bedrooms, desks and entertainment spaces.",
    descriptionFa: "Ú†Ø±Ø§Øº Ù†ÙˆØ±Ù¾Ø±Ø¯Ø§Ø²ÛŒ Ø¨Ø±Ø§ÛŒ Ø§ØªØ§Ù‚ØŒ Ù…ÛŒØ² Ú©Ø§Ø± Ùˆ ÙØ¶Ø§ÛŒ Ø³Ø±Ú¯Ø±Ù…ÛŒ.",
    price: 36,
    compareAtPrice: 49,
    sku: "YAS-GAL-001",
  },
  {
    id: "vision-smart-display",
    categoryId: "smart-tech",
    en: "Vision Smart Display",
    fa: "Ù†Ù…Ø§ÛŒØ´Ú¯Ø± Ù‡ÙˆØ´Ù…Ù†Ø¯ ÙˆÛŒÚ˜Ù†",
    descriptionEn: "Smart display for home information and entertainment.",
    descriptionFa: "Ù†Ù…Ø§ÛŒØ´Ú¯Ø± Ù‡ÙˆØ´Ù…Ù†Ø¯ Ø¨Ø±Ø§ÛŒ Ø§Ø·Ù„Ø§Ø¹Ø§Øª Ùˆ Ø³Ø±Ú¯Ø±Ù…ÛŒ Ø®Ø§Ù†Ù‡.",
    price: 129,
    compareAtPrice: 159,
    sku: "YAS-VSD-001",
  },
  {
    id: "smart-home-hub",
    categoryId: "smart-tech",
    en: "Smart Home Hub",
    fa: "Ù‡Ø§Ø¨ Ø®Ø§Ù†Ù‡ Ù‡ÙˆØ´Ù…Ù†Ø¯",
    descriptionEn: "Central hub for connected smart-home devices.",
    descriptionFa: "Ù‡Ø§Ø¨ Ù…Ø±Ú©Ø²ÛŒ Ø¨Ø±Ø§ÛŒ Ù…Ø¯ÛŒØ±ÛŒØª ØªØ¬Ù‡ÛŒØ²Ø§Øª Ø®Ø§Ù†Ù‡ Ù‡ÙˆØ´Ù…Ù†Ø¯.",
    price: 99,
    compareAtPrice: 129,
    sku: "YAS-SHH-006",
  },
  {
    id: "nova-travel-pack",
    categoryId: "lifestyle",
    en: "Nova Travel Pack",
    fa: "Ú©ÙˆÙ„Ù‡ Ø³ÙØ± Ù†ÙˆØ§",
    descriptionEn: "Practical travel backpack with organized storage.",
    descriptionFa: "Ú©ÙˆÙ„Ù‡ Ú©Ø§Ø±Ø¨Ø±Ø¯ÛŒ Ø³ÙØ± Ø¨Ø§ ÙØ¶Ø§ÛŒ ØªÙÚ©ÛŒÚ©â€ŒØ´Ø¯Ù‡.",
    price: 48,
    compareAtPrice: 65,
    sku: "YAS-NTP-001",
  },
  {
    id: "gaming-mechanical-keyboard",
    categoryId: "gaming",
    en: "Gaming Mechanical Keyboard",
    fa: "Ú©ÛŒØ¨ÙˆØ±Ø¯ Ù…Ú©Ø§Ù†ÛŒÚ©ÛŒ Ú¯ÛŒÙ…ÛŒÙ†Ú¯",
    descriptionEn: "Mechanical keyboard designed for gaming and fast response.",
    descriptionFa: "Ú©ÛŒØ¨ÙˆØ±Ø¯ Ù…Ú©Ø§Ù†ÛŒÚ©ÛŒ Ø¨Ø±Ø§ÛŒ Ú¯ÛŒÙ…ÛŒÙ†Ú¯ Ø¨Ø§ Ù¾Ø§Ø³Ø® Ø³Ø±ÛŒØ¹.",
    price: 69,
    compareAtPrice: 89,
    sku: "YAS-GMK-007",
  },
  {
    id: "gaming-wireless-mouse",
    categoryId: "gaming",
    en: "Gaming Wireless Mouse",
    fa: "Ù…Ø§ÙˆØ³ Ø¨ÛŒâ€ŒØ³ÛŒÙ… Ú¯ÛŒÙ…ÛŒÙ†Ú¯",
    descriptionEn: "Low-latency wireless gaming mouse with ergonomic design.",
    descriptionFa: "Ù…Ø§ÙˆØ³ Ø¨ÛŒâ€ŒØ³ÛŒÙ… Ú¯ÛŒÙ…ÛŒÙ†Ú¯ Ø¨Ø§ ØªØ£Ø®ÛŒØ± Ú©Ù… Ùˆ Ø·Ø±Ø§Ø­ÛŒ Ø§Ø±Ú¯ÙˆÙ†ÙˆÙ…ÛŒÚ©.",
    price: 54,
    compareAtPrice: 69,
    sku: "YAS-GWM-008",
  },
  {
    id: "gaming-headset",
    categoryId: "gaming",
    en: "Gaming Headset",
    fa: "Ù‡Ø¯Ø³Øª Ú¯ÛŒÙ…ÛŒÙ†Ú¯",
    descriptionEn: "Gaming headset with microphone for competitive play.",
    descriptionFa: "Ù‡Ø¯Ø³Øª Ú¯ÛŒÙ…ÛŒÙ†Ú¯ Ø¯Ø§Ø±Ø§ÛŒ Ù…ÛŒÚ©Ø±ÙˆÙÙˆÙ† Ø¨Ø±Ø§ÛŒ Ø¨Ø§Ø²ÛŒ Ø±Ù‚Ø§Ø¨ØªÛŒ.",
    price: 64,
    compareAtPrice: 84,
    sku: "YAS-GHS-009",
  },
  {
    id: "gaming-controller",
    categoryId: "gaming",
    en: "Wireless Gaming Controller",
    fa: "Ø¯Ø³ØªÙ‡ Ø¨Ø§Ø²ÛŒ Ø¨ÛŒâ€ŒØ³ÛŒÙ…",
    descriptionEn: "Wireless controller for console and PC gaming.",
    descriptionFa: "Ø¯Ø³ØªÙ‡ Ø¨Ø§Ø²ÛŒ Ø¨ÛŒâ€ŒØ³ÛŒÙ… Ø¨Ø±Ø§ÛŒ Ú©Ù†Ø³ÙˆÙ„ Ùˆ Ú©Ø§Ù…Ù¾ÛŒÙˆØªØ±.",
    price: 49,
    compareAtPrice: 65,
    sku: "YAS-WGC-010",
  },
  {
    id: "gaming-monitor-24",
    categoryId: "gaming",
    en: "24 Inch Gaming Monitor",
    fa: "Ù…Ø§Ù†ÛŒØªÙˆØ± Ú¯ÛŒÙ…ÛŒÙ†Ú¯ Û²Û´ Ø§ÛŒÙ†Ú†",
    descriptionEn: "Fast gaming monitor for smooth desktop gameplay.",
    descriptionFa: "Ù…Ø§Ù†ÛŒØªÙˆØ± Ø³Ø±ÛŒØ¹ Ø¨Ø±Ø§ÛŒ ØªØ¬Ø±Ø¨Ù‡ Ø±ÙˆØ§Ù† Ø¨Ø§Ø²ÛŒ.",
    price: 149,
    compareAtPrice: 179,
    sku: "YAS-GM24-011",
  },
  {
    id: "android-smartphone-x",
    categoryId: "mobile",
    en: "Smartphone X",
    fa: "Ú¯ÙˆØ´ÛŒ Ù‡ÙˆØ´Ù…Ù†Ø¯ X",
    descriptionEn: "Modern smartphone for everyday communication and media.",
    descriptionFa: "Ú¯ÙˆØ´ÛŒ Ù‡ÙˆØ´Ù…Ù†Ø¯ Ù…Ø¯Ø±Ù† Ø¨Ø±Ø§ÛŒ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø±ÙˆØ²Ù…Ø±Ù‡ Ùˆ Ø³Ø±Ú¯Ø±Ù…ÛŒ.",
    price: 299,
    compareAtPrice: 349,
    sku: "YAS-SPX-012",
  },
  {
    id: "compact-smartphone",
    categoryId: "mobile",
    en: "Compact Smartphone",
    fa: "Ú¯ÙˆØ´ÛŒ Ù‡ÙˆØ´Ù…Ù†Ø¯ Ú©Ø§Ù…Ù¾Ú©Øª",
    descriptionEn: "Compact smartphone designed for comfortable one-hand use.",
    descriptionFa: "Ú¯ÙˆØ´ÛŒ Ù‡ÙˆØ´Ù…Ù†Ø¯ Ø¬Ù…Ø¹â€ŒÙˆØ¬ÙˆØ± Ø¨Ø±Ø§ÛŒ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø±Ø§Ø­Øª Ø¨Ø§ ÛŒÚ© Ø¯Ø³Øª.",
    price: 229,
    compareAtPrice: 269,
    sku: "YAS-CS-013",
  },
  {
    id: "tablet-air",
    categoryId: "mobile",
    en: "Tablet Air",
    fa: "ØªØ¨Ù„Øª Air",
    descriptionEn: "Light tablet for study, entertainment and browsing.",
    descriptionFa: "ØªØ¨Ù„Øª Ø³Ø¨Ú© Ø¨Ø±Ø§ÛŒ Ù…Ø·Ø§Ù„Ø¹Ù‡ØŒ Ø³Ø±Ú¯Ø±Ù…ÛŒ Ùˆ ÙˆØ¨â€ŒÚ¯Ø±Ø¯ÛŒ.",
    price: 199,
    compareAtPrice: 239,
    sku: "YAS-TA-014",
  },
  {
    id: "usb-c-power-bank",
    categoryId: "mobile",
    en: "USB-C Power Bank",
    fa: "Ù¾Ø§ÙˆØ±Ø¨Ø§Ù†Ú© USB-C",
    descriptionEn: "Portable power bank with USB-C charging.",
    descriptionFa: "Ù¾Ø§ÙˆØ±Ø¨Ø§Ù†Ú© Ù‚Ø§Ø¨Ù„ Ø­Ù…Ù„ Ø¨Ø§ Ø´Ø§Ø±Ú˜ USB-C.",
    price: 39,
    compareAtPrice: 49,
    sku: "YAS-PB-015",
  },
  {
    id: "air-fryer-digital",
    categoryId: "kitchen",
    en: "Digital Air Fryer",
    fa: "Ø³Ø±Ø®â€ŒÚ©Ù† Ø¨Ø¯ÙˆÙ† Ø±ÙˆØºÙ† Ø¯ÛŒØ¬ÛŒØªØ§Ù„",
    descriptionEn: "Digital air fryer for convenient low-oil cooking.",
    descriptionFa: "Ø³Ø±Ø®â€ŒÚ©Ù† Ø¨Ø¯ÙˆÙ† Ø±ÙˆØºÙ† Ø¯ÛŒØ¬ÛŒØªØ§Ù„ Ø¨Ø±Ø§ÛŒ Ø¢Ø´Ù¾Ø²ÛŒ Ø±Ø§Ø­Øªâ€ŒØªØ±.",
    price: 119,
    compareAtPrice: 149,
    sku: "YAS-AF-016",
  },
  {
    id: "kitchen-blender",
    categoryId: "kitchen",
    en: "Kitchen Blender",
    fa: "Ù…Ø®Ù„ÙˆØ·â€ŒÚ©Ù† Ø¢Ø´Ù¾Ø²Ø®Ø§Ù†Ù‡",
    descriptionEn: "Powerful blender for smoothies, sauces and drinks.",
    descriptionFa: "Ù…Ø®Ù„ÙˆØ·â€ŒÚ©Ù† Ù‚Ø¯Ø±ØªÙ…Ù†Ø¯ Ø¨Ø±Ø§ÛŒ Ø§Ø³Ù…ÙˆØªÛŒØŒ Ø³Ø³ Ùˆ Ù†ÙˆØ´ÛŒØ¯Ù†ÛŒ.",
    price: 69,
    compareAtPrice: 89,
    sku: "YAS-KB-017",
  },
  {
    id: "electric-kettle",
    categoryId: "kitchen",
    en: "Electric Kettle",
    fa: "Ú©ØªØ±ÛŒ Ø¨Ø±Ù‚ÛŒ",
    descriptionEn: "Fast electric kettle for tea, coffee and hot water.",
    descriptionFa: "Ú©ØªØ±ÛŒ Ø¨Ø±Ù‚ÛŒ Ø³Ø±ÛŒØ¹ Ø¨Ø±Ø§ÛŒ Ú†Ø§ÛŒØŒ Ù‚Ù‡ÙˆÙ‡ Ùˆ Ø¢Ø¨ Ú¯Ø±Ù….",
    price: 44,
    compareAtPrice: 59,
    sku: "YAS-EK-018",
  },
  {
    id: "coffee-maker",
    categoryId: "kitchen",
    en: "Home Coffee Maker",
    fa: "Ù‚Ù‡ÙˆÙ‡â€ŒØ³Ø§Ø² Ø®Ø§Ù†Ú¯ÛŒ",
    descriptionEn: "Compact coffee maker for everyday home brewing.",
    descriptionFa: "Ù‚Ù‡ÙˆÙ‡â€ŒØ³Ø§Ø² Ø¬Ù…Ø¹â€ŒÙˆØ¬ÙˆØ± Ø¨Ø±Ø§ÛŒ ØªÙ‡ÛŒÙ‡ Ù‚Ù‡ÙˆÙ‡ Ø±ÙˆØ²Ø§Ù†Ù‡.",
    price: 89,
    compareAtPrice: 119,
    sku: "YAS-CM-019",
  },
  {
    id: "kitchen-chopper",
    categoryId: "kitchen",
    en: "Mini Kitchen Chopper",
    fa: "Ø®Ø±Ø¯Ú©Ù† Ú©ÙˆÚ†Ú© Ø¢Ø´Ù¾Ø²Ø®Ø§Ù†Ù‡",
    descriptionEn: "Compact food chopper for everyday kitchen preparation.",
    descriptionFa: "Ø®Ø±Ø¯Ú©Ù† Ú©ÙˆÚ†Ú© Ø¨Ø±Ø§ÛŒ Ø¢Ù…Ø§Ø¯Ù‡â€ŒØ³Ø§Ø²ÛŒ Ø±ÙˆØ²Ù…Ø±Ù‡ Ù…ÙˆØ§Ø¯ ØºØ°Ø§ÛŒÛŒ.",
    price: 32,
    compareAtPrice: 42,
    sku: "YAS-KC-020",
  },
  {
    id: "kitchen-scale",
    categoryId: "kitchen",
    en: "Digital Kitchen Scale",
    fa: "ØªØ±Ø§Ø²Ùˆ Ø¯ÛŒØ¬ÛŒØªØ§Ù„ Ø¢Ø´Ù¾Ø²Ø®Ø§Ù†Ù‡",
    descriptionEn: "Precise digital scale for cooking and baking.",
    descriptionFa: "ØªØ±Ø§Ø²Ùˆ Ø¯ÛŒØ¬ÛŒØªØ§Ù„ Ø¯Ù‚ÛŒÙ‚ Ø¨Ø±Ø§ÛŒ Ø¢Ø´Ù¾Ø²ÛŒ Ùˆ Ø´ÛŒØ±ÛŒÙ†ÛŒâ€ŒÙ¾Ø²ÛŒ.",
    price: 24,
    compareAtPrice: 32,
    sku: "YAS-KS-021",
  },
  {
    id: "travel-carry-bag",
    categoryId: "bags",
    en: "Travel Carry Bag",
    fa: "Ú©ÛŒÙ Ø¯Ø³ØªÛŒ Ø³ÙØ±",
    descriptionEn: "Spacious carry bag for short trips and daily travel.",
    descriptionFa: "Ú©ÛŒÙ Ø¬Ø§Ø¯Ø§Ø± Ø¨Ø±Ø§ÛŒ Ø³ÙØ±Ù‡Ø§ÛŒ Ú©ÙˆØªØ§Ù‡ Ùˆ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø±ÙˆØ²Ù…Ø±Ù‡.",
    price: 55,
    compareAtPrice: 72,
    sku: "YAS-TCB-022",
  },
  {
    id: "urban-crossbody-bag",
    categoryId: "bags",
    en: "Urban Crossbody Bag",
    fa: "Ú©ÛŒÙ Ø¯ÙˆØ´ÛŒ Ø´Ù‡Ø±ÛŒ",
    descriptionEn: "Compact crossbody bag for everyday essentials.",
    descriptionFa: "Ú©ÛŒÙ Ø¯ÙˆØ´ÛŒ Ø¬Ù…Ø¹â€ŒÙˆØ¬ÙˆØ± Ø¨Ø±Ø§ÛŒ ÙˆØ³Ø§ÛŒÙ„ Ø¶Ø±ÙˆØ±ÛŒ Ø±ÙˆØ²Ù…Ø±Ù‡.",
    price: 38,
    compareAtPrice: 49,
    sku: "YAS-UCB-023",
  },
  {
    id: "laptop-backpack",
    categoryId: "bags",
    en: "Laptop Backpack",
    fa: "Ú©ÙˆÙ„Ù‡ Ù„Ù¾â€ŒØªØ§Ù¾",
    descriptionEn: "Protective backpack with a dedicated laptop compartment.",
    descriptionFa: "Ú©ÙˆÙ„Ù‡ Ù…Ø­Ø§ÙØ¸ Ø¨Ø§ Ù…Ø­ÙØ¸Ù‡ Ø§Ø®ØªØµØ§ØµÛŒ Ù„Ù¾â€ŒØªØ§Ù¾.",
    price: 62,
    compareAtPrice: 79,
    sku: "YAS-LB-024",
  },
  {
    id: "classic-wallet",
    categoryId: "bags",
    en: "Classic Wallet",
    fa: "Ú©ÛŒÙ Ù¾ÙˆÙ„ Ú©Ù„Ø§Ø³ÛŒÚ©",
    descriptionEn: "Slim everyday wallet with organized card storage.",
    descriptionFa: "Ú©ÛŒÙ Ù¾ÙˆÙ„ Ø¨Ø§Ø±ÛŒÚ© Ø¨Ø§ ÙØ¶Ø§ÛŒ Ù…Ù†Ø¸Ù… Ø¨Ø±Ø§ÛŒ Ú©Ø§Ø±Øªâ€ŒÙ‡Ø§.",
    price: 25,
    compareAtPrice: 35,
    sku: "YAS-CW-025",
  },
  {
    id: "minimal-necklace",
    categoryId: "jewelry",
    en: "Minimal Necklace",
    fa: "Ú¯Ø±Ø¯Ù†Ø¨Ù†Ø¯ Ù…ÛŒÙ†ÛŒÙ…Ø§Ù„",
    descriptionEn: "Minimal necklace for everyday styling.",
    descriptionFa: "Ú¯Ø±Ø¯Ù†Ø¨Ù†Ø¯ Ù…ÛŒÙ†ÛŒÙ…Ø§Ù„ Ø¨Ø±Ø§ÛŒ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø±ÙˆØ²Ù…Ø±Ù‡.",
    price: 35,
    compareAtPrice: 49,
    sku: "YAS-MN-026",
  },
  {
    id: "classic-bracelet",
    categoryId: "jewelry",
    en: "Classic Bracelet",
    fa: "Ø¯Ø³ØªØ¨Ù†Ø¯ Ú©Ù„Ø§Ø³ÛŒÚ©",
    descriptionEn: "Simple bracelet suitable for everyday outfits.",
    descriptionFa: "Ø¯Ø³ØªØ¨Ù†Ø¯ Ø³Ø§Ø¯Ù‡ Ù…Ù†Ø§Ø³Ø¨ Ø§Ø³ØªØ§ÛŒÙ„ Ø±ÙˆØ²Ù…Ø±Ù‡.",
    price: 29,
    compareAtPrice: 39,
    sku: "YAS-CB-027",
  },
  {
    id: "silver-style-ring",
    categoryId: "jewelry",
    en: "Silver Style Ring",
    fa: "Ø§Ù†Ú¯Ø´ØªØ± Ù†Ù‚Ø±Ù‡â€ŒØ§ÛŒ",
    descriptionEn: "Clean silver-style ring with a timeless design.",
    descriptionFa: "Ø§Ù†Ú¯Ø´ØªØ± Ø¨Ø§ Ø¸Ø§Ù‡Ø± Ù†Ù‚Ø±Ù‡â€ŒØ§ÛŒ Ùˆ Ø·Ø±Ø§Ø­ÛŒ Ø³Ø§Ø¯Ù‡ Ùˆ Ù…Ø§Ù†Ø¯Ú¯Ø§Ø±.",
    price: 42,
    compareAtPrice: 55,
    sku: "YAS-SSR-028",
  },
  {
    id: "gaming-laptop-15",
    categoryId: "computing",
    en: "Gaming Laptop 15",
    fa: "Ù„Ù¾â€ŒØªØ§Ù¾ Ú¯ÛŒÙ…ÛŒÙ†Ú¯ Û±Ûµ Ø§ÛŒÙ†Ú†",
    descriptionEn: "Powerful gaming laptop for modern games, graphics and demanding workloads.",
    descriptionFa: "Ù„Ù¾â€ŒØªØ§Ù¾ Ú¯ÛŒÙ…ÛŒÙ†Ú¯ Ù‚Ø¯Ø±ØªÙ…Ù†Ø¯ Ø¨Ø±Ø§ÛŒ Ø¨Ø§Ø²ÛŒâ€ŒÙ‡Ø§ÛŒ Ø¬Ø¯ÛŒØ¯ØŒ Ú¯Ø±Ø§ÙÛŒÚ© Ùˆ Ú©Ø§Ø±Ù‡Ø§ÛŒ Ø³Ù†Ú¯ÛŒÙ†.",
    price: 899,
    compareAtPrice: 999,
    sku: "YAS-GL15-030",
  },
  {
    id: "work-laptop-air",
    categoryId: "computing",
    en: "Work Laptop Air",
    fa: "Ù„Ù¾â€ŒØªØ§Ù¾ Ø³Ø¨Ú© Ú©Ø§Ø±ÛŒ",
    descriptionEn: "Lightweight laptop for office work, study, browsing and everyday productivity.",
    descriptionFa: "Ù„Ù¾â€ŒØªØ§Ù¾ Ø³Ø¨Ú© Ø¨Ø±Ø§ÛŒ Ú©Ø§Ø± Ø§Ø¯Ø§Ø±ÛŒØŒ Ù…Ø·Ø§Ù„Ø¹Ù‡ØŒ ÙˆØ¨â€ŒÚ¯Ø±Ø¯ÛŒ Ùˆ Ø¨Ù‡Ø±Ù‡â€ŒÙˆØ±ÛŒ Ø±ÙˆØ²Ø§Ù†Ù‡.",
    price: 699,
    compareAtPrice: 799,
    sku: "YAS-WLA-031",
  },
  {
    id: "creator-laptop-pro",
    categoryId: "computing",
    en: "Creator Laptop Pro",
    fa: "Ù„Ù¾â€ŒØªØ§Ù¾ Ø­Ø±ÙÙ‡â€ŒØ§ÛŒ ØªÙˆÙ„ÛŒØ¯ Ù…Ø­ØªÙˆØ§",
    descriptionEn: "High-performance laptop for video editing, creative work and professional applications.",
    descriptionFa: "Ù„Ù¾â€ŒØªØ§Ù¾ Ù‚Ø¯Ø±ØªÙ…Ù†Ø¯ Ø¨Ø±Ø§ÛŒ ØªØ¯ÙˆÛŒÙ† ÙˆÛŒØ¯Ø¦ÙˆØŒ ØªÙˆÙ„ÛŒØ¯ Ù…Ø­ØªÙˆØ§ Ùˆ Ù†Ø±Ù…â€ŒØ§ÙØ²Ø§Ø±Ù‡Ø§ÛŒ Ø­Ø±ÙÙ‡â€ŒØ§ÛŒ.",
    price: 1199,
    compareAtPrice: 1349,
    sku: "YAS-CLP-032",
  },
  {
    id: "ultra-light-laptop",
    categoryId: "computing",
    en: "Ultra Light Laptop",
    fa: "Ù„Ù¾â€ŒØªØ§Ù¾ ÙÙˆÙ‚ Ø³Ø¨Ú©",
    descriptionEn: "Slim and lightweight laptop for travel, study and mobile productivity.",
    descriptionFa: "Ù„Ù¾â€ŒØªØ§Ù¾ Ø¨Ø§Ø±ÛŒÚ© Ùˆ Ø³Ø¨Ú© Ø¨Ø±Ø§ÛŒ Ø³ÙØ±ØŒ Ù…Ø·Ø§Ù„Ø¹Ù‡ Ùˆ Ú©Ø§Ø± Ø¯Ø± Ø­Ø±Ú©Øª.",
    price: 749,
    compareAtPrice: 849,
    sku: "YAS-ULL-033",
  },
  {
    id: "pro-creator-monitor",
    categoryId: "computing",
    en: "Pro Creator Monitor",
    fa: "Ù…Ø§Ù†ÛŒØªÙˆØ± Ø­Ø±ÙÙ‡â€ŒØ§ÛŒ ØªÙˆÙ„ÛŒØ¯ Ù…Ø­ØªÙˆØ§",
    descriptionEn: "High-resolution monitor for creative work, design and professional computing.",
    descriptionFa: "Ù…Ø§Ù†ÛŒØªÙˆØ± Ø¨Ø§ ÙˆØ¶ÙˆØ­ Ø¨Ø§Ù„Ø§ Ø¨Ø±Ø§ÛŒ ØªÙˆÙ„ÛŒØ¯ Ù…Ø­ØªÙˆØ§ØŒ Ø·Ø±Ø§Ø­ÛŒ Ùˆ Ú©Ø§Ø± Ø­Ø±ÙÙ‡â€ŒØ§ÛŒ.",
    price: 329,
    compareAtPrice: 379,
    sku: "YAS-PCM-034",
  },
  {
    id: "daily-earrings",
    categoryId: "jewelry",
    en: "Daily Earrings",
    fa: "Ú¯ÙˆØ´ÙˆØ§Ø±Ù‡ Ø±ÙˆØ²Ù…Ø±Ù‡",
    descriptionEn: "Lightweight earrings designed for everyday wear.",
    descriptionFa: "Ú¯ÙˆØ´ÙˆØ§Ø±Ù‡ Ø³Ø¨Ú© Ø¨Ø±Ø§ÛŒ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø±ÙˆØ²Ù…Ø±Ù‡.",
    price: 27,
    compareAtPrice: 36,
    sku: "YAS-DE-029",
  },
  {
    id: "classic-sunglasses",
    categoryId: "personal-care",
    en: "Classic Sunglasses",
    fa: "Ø¹ÛŒÙ†Ú© Ø¢ÙØªØ§Ø¨ÛŒ Ú©Ù„Ø§Ø³ÛŒÚ©",
    descriptionEn: "Classic sunglasses with a versatile everyday shape.",
    descriptionFa: "Ø¹ÛŒÙ†Ú© Ø¢ÙØªØ§Ø¨ÛŒ Ú©Ù„Ø§Ø³ÛŒÚ© Ø¨Ø§ ÙØ±Ù… Ù…Ù†Ø§Ø³Ø¨ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø±ÙˆØ²Ù…Ø±Ù‡.",
    price: 45,
    compareAtPrice: 59,
    sku: "YAS-CSG-030",
  },
  {
    id: "electric-trimmer",
    categoryId: "personal-care",
    en: "Electric Trimmer",
    fa: "Ù…Ø§Ø´ÛŒÙ† Ø§ØµÙ„Ø§Ø­ Ø¨Ø±Ù‚ÛŒ",
    descriptionEn: "Rechargeable electric trimmer for personal grooming.",
    descriptionFa: "Ù…Ø§Ø´ÛŒÙ† Ø§ØµÙ„Ø§Ø­ Ø´Ø§Ø±Ú˜ÛŒ Ø¨Ø±Ø§ÛŒ Ù…Ø±Ø§Ù‚Ø¨Øª Ø´Ø®ØµÛŒ.",
    price: 58,
    compareAtPrice: 75,
    sku: "YAS-ET-031",
  },
  {
    id: "hair-dryer-compact",
    categoryId: "personal-care",
    en: "Compact Hair Dryer",
    fa: "Ø³Ø´ÙˆØ§Ø± Ú©Ø§Ù…Ù¾Ú©Øª",
    descriptionEn: "Compact hair dryer for home and travel use.",
    descriptionFa: "Ø³Ø´ÙˆØ§Ø± Ø¬Ù…Ø¹â€ŒÙˆØ¬ÙˆØ± Ø¨Ø±Ø§ÛŒ Ø®Ø§Ù†Ù‡ Ùˆ Ø³ÙØ±.",
    price: 47,
    compareAtPrice: 62,
    sku: "YAS-CHD-032",
  },
  {
    id: "desk-organizer",
    categoryId: "home",
    en: "Smart Desk Organizer",
    fa: "Ù†Ø¸Ù…â€ŒØ¯Ù‡Ù†Ø¯Ù‡ Ù‡ÙˆØ´Ù…Ù†Ø¯ Ù…ÛŒØ²",
    descriptionEn: "Modern organizer for keeping a workspace tidy.",
    descriptionFa: "Ù†Ø¸Ù…â€ŒØ¯Ù‡Ù†Ø¯Ù‡ Ù…Ø¯Ø±Ù† Ø¨Ø±Ø§ÛŒ Ù…Ø±ØªØ¨ Ù†Ú¯Ù‡ Ø¯Ø§Ø´ØªÙ† Ù…ÛŒØ² Ú©Ø§Ø±.",
    price: 28,
    compareAtPrice: 38,
    sku: "YAS-DO-033",
  },
  {
    id: "portable-projector",
    categoryId: "smart-tech",
    en: "Portable Projector",
    fa: "Ù¾Ø±ÙˆÚ˜Ú©ØªÙˆØ± Ù‚Ø§Ø¨Ù„ Ø­Ù…Ù„",
    descriptionEn: "Compact projector for movies, presentations and travel.",
    descriptionFa: "Ù¾Ø±ÙˆÚ˜Ú©ØªÙˆØ± Ø¬Ù…Ø¹â€ŒÙˆØ¬ÙˆØ± Ø¨Ø±Ø§ÛŒ ÙÛŒÙ„Ù…ØŒ Ø§Ø±Ø§Ø¦Ù‡ Ùˆ Ø³ÙØ±.",
    price: 159,
    compareAtPrice: 199,
    sku: "YAS-PP-034",
  },
  {
    id: "smart-led-strip",
    categoryId: "smart-tech",
    en: "Smart LED Strip",
    fa: "Ù†ÙˆØ§Ø± LED Ù‡ÙˆØ´Ù…Ù†Ø¯",
    descriptionEn: "Smart LED strip for ambient room and desk lighting.",
    descriptionFa: "Ù†ÙˆØ§Ø± LED Ù‡ÙˆØ´Ù…Ù†Ø¯ Ø¨Ø±Ø§ÛŒ Ù†ÙˆØ±Ù¾Ø±Ø¯Ø§Ø²ÛŒ Ø§ØªØ§Ù‚ Ùˆ Ù…ÛŒØ².",
    price: 31,
    compareAtPrice: 42,
    sku: "YAS-SLS-035",
  },
  {
    id: "portable-bluetooth-speaker",
    categoryId: "audio",
    en: "Portable Bluetooth Speaker",
    fa: "Ø§Ø³Ù¾ÛŒÚ©Ø± Ø¨Ù„ÙˆØªÙˆØ« Ù‚Ø§Ø¨Ù„ Ø­Ù…Ù„",
    descriptionEn: "Portable Bluetooth speaker for home and outdoor listening.",
    descriptionFa: "Ø§Ø³Ù¾ÛŒÚ©Ø± Ø¨Ù„ÙˆØªÙˆØ« Ù‚Ø§Ø¨Ù„ Ø­Ù…Ù„ Ø¨Ø±Ø§ÛŒ Ø®Ø§Ù†Ù‡ Ùˆ ÙØ¶Ø§ÛŒ Ø¨ÛŒØ±ÙˆÙ†.",
    price: 52,
    compareAtPrice: 69,
    sku: "YAS-PBS-036",
  },
  {
    id: "foldable-travel-backpack",
    categoryId: "bags",
    en: "Foldable Travel Backpack",
    fa: "Ú©ÙˆÙ„Ù‡ Ø³ÙØ±ÛŒ ØªØ§Ø´Ùˆ",
    descriptionEn: "Light foldable backpack for travel and day trips.",
    descriptionFa: "Ú©ÙˆÙ„Ù‡ Ø³Ø¨Ú© Ùˆ ØªØ§Ø´Ùˆ Ø¨Ø±Ø§ÛŒ Ø³ÙØ± Ùˆ Ú¯Ø±Ø¯Ø´ Ø±ÙˆØ²Ø§Ù†Ù‡.",
    price: 34,
    compareAtPrice: 45,
    sku: "YAS-FTB-037",
  },
  {
    id: "smart-temperature-mug",
    categoryId: "kitchen",
    en: "Smart Temperature Mug",
    fa: "Ù…Ø§Ú¯ Ú©Ù†ØªØ±Ù„ Ø¯Ù…Ø§",
    descriptionEn: "Modern mug designed to help maintain drink temperature.",
    descriptionFa: "Ù…Ø§Ú¯ Ù…Ø¯Ø±Ù† Ø¨Ø±Ø§ÛŒ Ú©Ù…Ú© Ø¨Ù‡ Ø­ÙØ¸ Ø¯Ù…Ø§ÛŒ Ù†ÙˆØ´ÛŒØ¯Ù†ÛŒ.",
    price: 41,
    compareAtPrice: 55,
    sku: "YAS-STM-038",
  },
  {
    id: "tablet-keyboard-case",
    categoryId: "mobile",
    en: "Tablet Keyboard Case",
    fa: "Ú©Ø§ÙˆØ± Ú©ÛŒØ¨ÙˆØ±Ø¯ ØªØ¨Ù„Øª",
    descriptionEn: "Protective tablet case with an integrated keyboard.",
    descriptionFa: "Ú©Ø§ÙˆØ± Ù…Ø­Ø§ÙØ¸ ØªØ¨Ù„Øª Ø¨Ø§ Ú©ÛŒØ¨ÙˆØ±Ø¯ Ø¯Ø§Ø®Ù„ÛŒ.",
    price: 57,
    compareAtPrice: 72,
    sku: "YAS-TKC-039",
  },
  {
    id: "travel-tech-organizer",
    categoryId: "bags",
    en: "Travel Tech Organizer",
    fa: "Ú©ÛŒÙ Ù†Ø¸Ù…â€ŒØ¯Ù‡Ù†Ø¯Ù‡ Ù„ÙˆØ§Ø²Ù… Ø¯ÛŒØ¬ÛŒØªØ§Ù„",
    descriptionEn: "Organizer pouch for chargers, cables and small electronics.",
    descriptionFa: "Ú©ÛŒÙ Ù†Ø¸Ù…â€ŒØ¯Ù‡Ù†Ø¯Ù‡ Ø¨Ø±Ø§ÛŒ Ø´Ø§Ø±Ú˜Ø±ØŒ Ú©Ø§Ø¨Ù„ Ùˆ Ù„ÙˆØ§Ø²Ù… Ø¯ÛŒØ¬ÛŒØªØ§Ù„ Ú©ÙˆÚ†Ú©.",
    price: 29,
    compareAtPrice: 39,
    sku: "YAS-TTO-040",
  },
];

export const products: Product[] = seedItems.map((item) => ({
  id: item.id,
  categoryId: item.categoryId,
  status: "active",
  createdAt: DATE,
  updatedAt: DATE,
}));

export const productLocalizations: ProductLocalization[] =
  seedItems.flatMap((item) => [
    {
      productId: item.id,
      locale: "en",
      name: item.en,
      description: item.descriptionEn,
    },
    {
      productId: item.id,
      locale: "fa",
      name: item.fa,
      description: item.descriptionFa,
    },
  ]);

export const productSeo: ProductSeo[] = seedItems.flatMap((item) => [
  {
    productId: item.id,
    locale: "en",
    slug: item.id,
  },
  {
    productId: item.id,
    locale: "fa",
    slug: item.id,
  },
]);

export const productSkus: ProductSku[] = seedItems.map((item) => ({
  id: `${item.id}-default`,
  productId: item.id,
  sku: item.sku,
  attributes: [],
  status: "active",
  createdAt: DATE,
  updatedAt: DATE,
}));

export const productPrices: ProductPrice[] = seedItems.map((item) => ({
  id: `price-${item.id}`,
  skuId: `${item.id}-default`,
  currency: "USD",
  price: item.price,
  compareAtPrice: item.compareAtPrice,
  status: "active",
}));

export const productMedia: ProductMediaItem[] = seedItems.map((item) => ({
  id: `media-${item.id}-01`,
  productId: item.id,
  type: "image",
  url: `/products/${item.id}.webp`,
  alt: item.en,
  mimeType: "image/webp",
  sortOrder: 0,
  status: "active",
}));

export const productAttributes: ProductAttribute[] = [];

export const productSpecifications: ProductSpecification[] = [];

